export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const SET_APPOINTMENTS = "SET_APPOINTMENTS";
export const BOOK_APPOINTMENT = "BOOK_APPOINTMENT";
export const BOOK_APPOINTMENT_SUCCESS = "BOOK_APPOINTMENT_SUCCESS";